export default interface IEntry {
  // Id of this item
  id?: string | null;

  // The question
  question: string;

  // The answer to the question
  answer: string;

  // Additional context, used when we are going to generate
  // other questions based on this on
  context: string;

  // Source question, used to auto-derive this.
  // i.e. this id was fed to the ai to generate this
  // question + answer pair.
  // this is null for questions that are generated by
  // humans.
  generated_by?: string | null;

  // Number of votes, negative votes
  // would mean the item should be ignored.
  votes: number;

  // Users that have rated this item, mainly used to track
  // who has already voted for things.
  users: string[];
}
